"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(n):
    a = 1
    b = 2
    if n <= 0:
        print("Incorrect input")
    elif n == 1:
        return 1
    elif n==2:
        return 2
    else:
        for i in range(2,n):
            c = a + b
            a = b
            b = c
        return b

x=0
for i in range(1,35):
    if fibonacci(i)<4000000 and fibonacci(i)%2==0:
        x+=fibonacci(i)

print(x)#>>>fibonacci(35)>4000000
